#!/bin/bash

echo "==========================================="
echo "Azure API Management Terraform Fix Guide"
echo "==========================================="
echo ""

echo "The issue is in your Terraform configuration. The APIM backend URL includes '/api'"
echo "but your backend already serves at '/api', causing path duplication."
echo ""
echo "Current configuration (main.tf line 234):"
echo '  service_url = "http://${azurerm_linux_virtual_machine.main.private_ip_address}:3001/api"'
echo ""
echo "This results in APIM calling: http://VM-IP:3001/api/api/products"
echo ""
echo "SOLUTION:"
echo "========="
echo "Update terraform/azure/main.tf line 234 to remove the /api suffix:"
echo ""
echo "FROM:"
echo '  service_url = "http://${azurerm_linux_virtual_machine.main.private_ip_address}:3001/api"'
echo ""
echo "TO:"
echo '  service_url = "http://${azurerm_linux_virtual_machine.main.private_ip_address}:3001"'
echo ""
echo "Then run:"
echo "  cd terraform/azure"
echo "  terraform plan"
echo "  terraform apply"
echo ""
echo "This will update APIM to correctly proxy requests to your backend."
echo ""
echo "Alternative Quick Fix (without Terraform):"
echo "========================================="
echo "You can manually update the APIM backend in Azure Portal:"
echo "1. Go to Azure Portal > API Management > APIs > VulnShop API"
echo "2. Click on 'Settings' tab"
echo "3. Change Service URL from:"
echo "   http://10.0.1.4:3001/api"
echo "   to:"
echo "   http://10.0.1.4:3001"
echo "4. Save changes"
echo ""
echo "===========================================" 