name: Continuous Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: |
          backend/package-lock.json
          frontend/package-lock.json
    
    # Backend checks
    - name: Install backend dependencies
      working-directory: ./backend
      run: npm ci
    
    - name: Check backend code
      working-directory: ./backend
      run: |
        echo "✅ Backend dependencies installed successfully"
        # Add linting here if you have ESLint configured
        # npm run lint
    
    # Frontend checks
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci
    
    - name: Build frontend
      working-directory: ./frontend
      run: npm run build
    
    - name: Check frontend code
      working-directory: ./frontend
      run: |
        echo "✅ Frontend built successfully"
        # Add linting here if you have ESLint configured
        # npm run lint
    
    # Security scan (optional)
    - name: Run security audit
      run: |
        echo "🔒 Running security audit..."
        cd backend && npm audit --audit-level=high || true
        cd ../frontend && npm audit --audit-level=high || true
    
    # Notify on success (optional)
    - name: Deployment notification
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        echo "✅ Code pushed to main branch successfully!"
        echo "📌 Remember to run the refresh script on your VM:"
        echo "   ssh azureuser@your-vm-ip"
        echo "   cd /home/azureuser/vulnshop"
        echo "   ./refresh-deployment.sh" 